### ISSUE TITLE
help

### ISSUE THREAD

**Issue by TheRealPiggyWiggy** [dnasdw/3dstool#10]
i am trying to open pokemon alpha sapphire but it its givning me Error:Error opening ticket

**Comment by TheRealPiggyWiggy** [comment]
i mean pokemon moon

**Comment by dnasdw** [comment]
There is no such error in 3dstool.

**Comment by dnasdw** [comment]
before retail?

2018-01-27 7:55 GMT+08:00 TheRealPiggyWiggy <notifications@github.com>:
