### ISSUE TITLE
Removing "-auto" strings in v1.1.0

### ISSUE THREAD

**Issue by Asia81** [dnasdw/3dstool#11]
`https://github.com/dnasdw/3dstool/issues/9`

> dnasdw commented on 6 Sep 2017 
> PS:--exh-auto-key, --exefs-auto-key, --exefs-top-auto-key and --romfs-auto-key will remove after 3dstool v1.1.0.
> 
> Asia81 commented on 6 Sep 2017
> When you say
> PS:--exh-auto-key, --exefs-auto-key, --exefs-top-auto-key and --romfs-auto-key will remove after 3dstool v1.1.0.
> 
> Does it mean it will not be anymore to write that? Will be automatically used?

Did you include this feature or not?
Because when I try to don't use them, I can't extract game files.

**Comment by dnasdw** [comment]
Work in progress, coming soon.
