### ISSUE TITLE
3dstool does not compile without tweaks

### ISSUE THREAD

**Issue by NWPlayer123** [dnasdw/3dstool#17]
I'm using MSYS2/mingw64, cloned repo, and was trying to use my own libraries, renamed dep to dep1 to make sure it didn't use it, and then ran
```
mkdir build && cd build
cmake -G "MSYS Makefiles" -DUSE_DEP=OFF ..
make
```

like suggested, but I had to change <capstone.h> in both code.h and code.cpp to <capstone/capstone.h>, and add capstone to the target_link_libraries() in src/CMakeLists.txt to get it to link right, thought I'd bring it up

**Comment by dnasdw** [comment]
It's don't support capstone version 4.0 or master now.
The include folder layout is different between v3 and v4.
USE_DEP means don't use the prebuilt files.
3dstool use capstone as source files, not a library.
