### ISSUE TITLE
ROM with incorrect encryption flag gives error

### ISSUE THREAD

**Issue by iskunk** [dnasdw/3dstool#18]
I have a ROM file in CXI format. It is decrypted, but the ROM's encryption flag is incorrect; it says the ROM is encrypted. (This looks like a common problem with 3DS ROM files, because I have two ROMs like this.)

When I try to unpack the CXI, I see this error:
```
$ 3dstool -x -t cxi -f pmd3.part0.cxi -v \
	--header header.bin \
	--extendedheader exheader.bin \
	--plainregion plain.bin \
	--exefs exefs.bin \
	--romfs romfs.bin
save: header.bin
save: exheader.bin
save: plain.bin
save: exefs.bin
save: romfs.bin
ERROR: extract file failed
```

GDB shows that the error happens in `CNcch::ExtractFile()`:
```
177				if (CExeFs::IsExeFsSuperBlock(exeFsSuperBlock))
(gdb) n
209					bResult = false;
(gdb) 
```

I thought that maybe if I give the `--not-encrypt` flag to tell 3dstool that the ROM is decrypted, it would work. But instead, I get a different error:
```
$ 3dstool -x -t cxi -f pmd3.part0.cxi -v \
	--not-encrypt \
	--header header.bin \
	--extendedheader exheader.bin \
	--plainregion plain.bin \
	--exefs exefs.bin \
	--romfs romfs.bin
ERROR: encrypt error
```

**Comment by dnasdw** [comment]
Please change the byte value to 0x04 at offset 0x18F of the cxi file, if the cxi is decrypted.
I don't want check the file dynamically.
--not-encrypt is for create cxi/cfa only, not for extract.

**Comment by iskunk** [comment]
I can fix my CXI file, but that is only my file. I downloaded this ROM from a Web site, so there are many other users who have a ROM file with an incorrect flag. And they probably don't know how to edit bytes in a binary file.

I can understand not wanting to check for encryption dynamically, as that can be complicated.

But it can be useful to have `--not-encrypt` for CXI extract, to override the ROM encryption flag. That way, I can tell 3dstool that the ROM is not encrypted, and ignore the incorrect flag, so there is no extract error.

**Comment by dnasdw** [comment]
You can use 3dstool v1.1.1 without any encrytion option.

**Comment by iskunk** [comment]
But an old version of the program won't have the bug fixes of newer versions, like the "CXI extract without exefs" bug.

I have two ROMs (from different Web sites) with this flag issue. They work fine in Citra, etc. but 3dstool gives an error. I think it was a bug in the ROM dumping tool, but nobody worried about it because Citra can run the ROMs even with the incorrect flag.

Because of this, there may be many ROM files out there with an incorrect encryption flag. So a user would need to override the flag with the correct value.

**Comment by dnasdw** [comment]
The "CXI extract without exefs" bug does not exist in fully extraction.
You can ask them to fix their ROMs.
This is not 3dstool's duty.

**Comment by iskunk** [comment]
But they will tell me there is nothing wrong with the ROM, because Citra can load it just fine.

If I tell them that 3dstool can't unpack the ROM because of an incorrect encryption flag, they'll say that this is a 3dstool bug.

They don't care about 3dstool, only Citra. It is unfortunate that all these buggy ROMs are out there, but that is how things are...

Anyway, 3dstool doesn't have to fix these buggy ROMs, it only needs to unpack them. After the ROM is unpacked, the flag doesn't matter anymore.

**Comment by dnasdw** [comment]
Download the original ROMs.
Do NOT download their garbage ROM.
3dstool will not support garbage.

**Comment by dnasdw** [comment]
You can find the original ROMs from here:
https://opgforum.net/index.php/forum/42-3ds
You can get the CRC32 of the .3ds files, and check with here:
http://www.3dsdb.com

The "normal" ROMs are error. 3dstool will not support error ROMs.

**Comment by iskunk** [comment]
I went to that site (first link), but it says I have to sign in.

When I try to create an account, it says "This site is set to Invite only, You will require an invite key to register."

I don't know if normal people can find these "original" ROMs...

(The second link is interesting. All those ROMs are "original"? They all work with 3dstool? I don't see those exact names on the ROM sites...)
