### ISSUE TITLE
3ds file grows by 200ish mb on rebuild?

### ISSUE THREAD

**Issue by gaberilde** [dnasdw/3dstool#19]
when extracting a 3ds file and rebuilding with this app, instead of the original file size, the file is always 512mb

can you fix this bug?

**Comment by dnasdw** [comment]
The min size of CARD2 is 512MB. It's official standard.

**Comment by gaberilde** [comment]
But my files seem to grow bigger even tho i never edited anything

**Comment by gaberilde** [comment]
Even a 700mb game grows in size its not right

**Comment by dnasdw** [comment]
Check your ROM file(or ncsdheader.bin).
The offset of CARDTYPE is 0x18D:
CARD1: 0x01
CARD2: 0x02
The min size of CARD1 is 128MB.
The min size of CARD2 is 512MB.
Check the original data, please visit http://www.3dsdb.com .
Check the last column "card".
If the data is not match your ROM, your ROM is modified.
You can change it back to the original by yourself, then create it.

**Comment by gaberilde** [comment]
It says card1 and the file is 300mb so thats correct right? this happens to mario kart 7 to it grows 200mb more then the original?

**Comment by gaberilde** [comment]
yes that fixed it thank you very much

PS: what does -cvt01267f do?

**Comment by dnasdw** [comment]
3dstool -cvt01267f cci 0.cxi 1.cfa 2.cfa 6.cfa 7.cfa output.3ds --header ncsdheader.bin --not-pad
is short for
3dstool -c -v -t cci -0 0.cxi -1 1.cfa -6 6.cfa -7 7.cfa -f output.3ds --header ncsdheader.bin --not-pad

**Comment by gaberilde** [comment]
werid because it works fine if i just add not pad on the command 
i think il just stick to that
thanks much
