### ISSUE TITLE
Problem with logo.darc.lz

### ISSUE THREAD

**Issue by BpyH64** [dnasdw/3dstool#21]
Some games contain the logo.darc.lz file in the exefs folder. The problem is that when unpacking exefs.bin, the logo.darc.lz file is not decrypted.(3dstool 1.2.5)

**Comment by dnasdw** [comment]
give me a product id, like CTR-X-YYYY

**Comment by BpyH64** [comment]
LBX: Little Battlers eXperience
0004000000147200
CTR-ADNP
Download and create CIA  with Villian3ds in 2017 year
https://fs20.fex.net/download/776008025

**Comment by dnasdw** [comment]
I try the japanese version of this game.
It's compressed.
You can uncompress it:
3dstool -uvf logo.darc.lz --compress-type lzex --compress-out logo.darc

**Comment by dnasdw** [comment]
Little Battlers eXperience EUR (0004000000147200) [IS].cia
The cxi of the cia is encrypted, I can't extract it.

**Comment by BpyH64** [comment]
eshop content unpack
ctrtool --contents=file --commonkey=64c5fd55dd3ad988325baaec5243db98 game.cia

**Comment by gaberilde** [comment]
thats version is like a million years old you be better building from source
