### ISSUE TITLE
ERROR: open file exefs/logo.darc.lz failed when trying to create cia

### ISSUE THREAD

**Issue by ThatWeirdAndrew** [dnasdw/3dstool#24]
I'm trying to edit the paper mario ss cia file. I'm following the guide [here](https://github.com/ihaveamac/3DS-rom-tools/wiki/Rebuilding-a-game-or-application-in-.cia-format). When I try to rebuild the exefs after extracting it, 3dstool throws out the error: `ERROR: open file exefs/logo.darc.lz failed`. I checked the directories and the logo never existed in a darc.lz file, it only exists in a bin file and a bmca.lz file.

**Comment by dnasdw** [comment]
3dstool version before v1.0.20, the logo file is logo.bcma.lz.
Starting from v1.0.20, this file is called logo.darc.lz.
I think the .bcma.lz extension is not reasonable, so I renamed it.

**Comment by dnasdw** [comment]
There is one more thing, some games, the logo is in the exefs, some are outside the exefs, but there is only one, don't mess up the position.
You only need to ensure that the extension of the file opened by 3dstool is the same as the actual file extension.

**Comment by ThatWeirdAndrew** [comment]
Alright, I replaced all instances of logo.darc.lz with logo.bcma.lz in the code and rebuilt it and it worked. Thanks for the help.
