### ISSUE TITLE
Trim & Untrim results in different hashes

### ISSUE THREAD

**Issue by Papermanzero** [dnasdw/3dstool#26]
I was looking for a tool to compress/trim 3DS games (Encrypted and decrypted) and also to decompress/untrim 3DS games to get the original roms back. The reason is to verify roms with no-intro and to archive them in a compressed form. If required the roms should be decompressed/untrimmed to verify the no-intro checksum. 

I tried now several roms with the trim/unteim feature. However it seems that roms larger than 4GB cannot be untrimmed. The hashes do not equal the original hashes from no-intro.

Steps to reproduce:
- Get a encrypted 3DS rom for Bravely Dedault
- Check the hash with the no-intro dat in romcenter
- Trim the 3DS rom with 3DSTool.
- check and verify that the size and hash of the rom is changed (smaller size)
- untrim the rom with 3DSTool 
-check the size and hash

You will recognize that after the unteimming process the size is correct, however the hash and file structure is wrong (verified with rom center)

**Comment by dnasdw** [comment]
```
名称: Bravely Default - Flying Fairy (JPN).3ds
大小: 2147483648 字节 (2048 MiB)
CRC32: 3E5C01E4

3dstool -rf "Bravely Default - Flying Fairy (JPN).3ds"

名称: Bravely Default - Flying Fairy (JPN).3ds
大小: 1965236736 字节 (1874 MiB)
CRC32: 6314820A

3dstool -pf "Bravely Default - Flying Fairy (JPN).3ds"

名称: Bravely Default - Flying Fairy (JPN).3ds
大小: 2147483648 字节 (2048 MiB)
CRC32: 3E5C01E4
```

```
名称: Bravely Default (EUR).3ds
大小: 4294967296 字节 (4096 MiB)
CRC32: 83FB5F9C

3dstool -rf "Bravely Default (EUR).3ds"

名称: Bravely Default (EUR).3ds
大小: 3508617216 字节 (3346 MiB)
CRC32: B59EA913

3dstool -pf "Bravely Default (EUR).3ds"

名称: Bravely Default (EUR).3ds
大小: 4294967296 字节 (4096 MiB)
CRC32: 83FB5F9C
```

```
名称: Bravely Default (USA).3ds
大小: 4294967296 字节 (4096 MiB)
CRC32: 0F123106

3dstool -rf "Bravely Default (USA).3ds"

名称: Bravely Default (USA).3ds
大小: 3504934912 字节 (3342 MiB)
CRC32: 8EF749A9

3dstool -pf "Bravely Default (USA).3ds"

名称: Bravely Default (USA).3ds
大小: 4294967296 字节 (4096 MiB)
CRC32: 0F123106
```

```
名称: Bravely Default - For the Sequel (JPN).3ds
大小: 4294967296 字节 (4096 MiB)
CRC32: FB356EE6

3dstool -rf "Bravely Default - For the Sequel (JPN).3ds"

名称: Bravely Default - For the Sequel (JPN).3ds
大小: 3498717184 字节 (3336 MiB)
CRC32: 6DC5F3F7

3dstool -pf "Bravely Default - For the Sequel (JPN).3ds"

名称: Bravely Default - For the Sequel (JPN).3ds
大小: 4294967296 字节 (4096 MiB)
CRC32: FB356EE6
```

**Comment by Papermanzero** [comment]
Thanks a lot! 
It is working!
Used the wrong command.
