### ISSUE TITLE
Backward LZ77 压缩问题

### ISSUE THREAD

**Issue by rcyggdra** [dnasdw/3dstool#29]
在给某些文件解压后重新压缩，放入游戏内虽然可以读取，但游戏出现错误；
有一部分文件出现这问题，其他同类文件是可以压缩同原始文件；
尝试对比原始文件，发现文件头里的文件大小值
[compactcommon.zip](https://github.com/dnasdw/3dstool/files/14071312/compactcommon.zip)
附件是DQ11的片头内容，原始文件头：
```
50 41 43 41 44 FD 04 00 00 01 FF FE CB 02 80 00
``` 
2次压缩后的文件头，大小值后面不是“00”而是“85”，然后整个压缩的主体内容前移了一个字节：
```
50 41 43 41 44 FD 04 85 00 FF FE CB 02 90 00 20
``` 
------------------------------------------

文件尾也有少许不同，原始文件尾：
```
00 00 00 00 00 1A FF FF 40 38 01 0A FC C4 03 00
``` 

2次压缩的文件尾：
```
00 00 00 00 1A FF FF FF 41 38 01 0B FC C4 03 00
```

**Comment by dnasdw** [comment]
从DQ11汉化人员得到的消息：因为DQ11的压缩不是标准blz，解压算法是兼容的，但压缩算法有区别。

**Comment by rcyggdra** [comment]
感谢解惑，最近在discord有几个老外捣鼓英文移植该游戏，我向他们推荐了你的工具，既然这压缩算法不一样，先让他们自己捣鼓吧。
