### ISSUE TITLE
Question about 2 entries...

### ISSUE THREAD

**Issue by eisnerguy1** [dnasdw/3dstool#7]
Sorry to bother you but, I had a small question regarding 3dstool.  On ext_key.txt, there's a listing for:
00400000018C400 	DC1941EF912EDE118D34C3596BF55FBA

this is apparently CTR-N-RMWA: ミュウ引換用ソフト (the Mew Trading App used in Japan for the RGBY VC releases).  

There’s also a listing for:
000400000018C500 	 9993FB59D175B8861C34F0F7D8BB831D 

this is CTR-N-RMWZ: Mew Trading App(E),

How did you come across the encrypted keys?  Might you also have the decrypted keys as well?

Any help would be greatly appreciated.

Thanks!

**Comment by dnasdw** [comment]
Replace %05X with any unique id you want (such as 018C5) in the url, then you can get the ext key.
Btw, regarding the url, plz refer to line 553 of ncch.cpp.
