### ISSUE TITLE
Antivirus is going crazy with 3dstool.exe

### ISSUE THREAD

**Issue by rafaelferreiraql** [dnasdw/3dstool#8]
And it's not only mine, either. [it has a 9/59 ratio on VirusTotal](https://www.virustotal.com/en/file/1ceb086dc81563bdb3c54aedbb0fc0df2e8655554e3d4b106987847ab2430126/analysis/), so some pretty reputable antiviruses are reporting it as a virus (of course, many others report as safe). What's causing it? Is there any way to revert it?

**Comment by dnasdw** [comment]
Maybe my computer is in the virus. Please compile it yourself.
