### ISSUE TITLE
Problem with decompressing code.bin in the latest release.

### ISSUE THREAD

**Issue by Asia81** [dnasdw/3dstool#9]
I have a problem with decompressing the code.bin file in the latest release of 3dstool (the one that use boot9 keys).
I can extract the DecryptedExeFS.bin file, extract its contents too.
(I extract from a clean game, not decrypted via Decrypt9 as it's not needed anymore with boot9 keys).

But when I try to decompress the code.bin file, 3dstool crash :
http://image.noelshack.com/fichiers/2017/36/2/1504595094-3dstool.png

I have the same error with ctrtool, I got "Error allocating memory" :
http://image.noelshack.com/fichiers/2017/36/2/1504595120-ctrtool.png

If I don't try to decompress, the extraction work fine, but the code.bin make the rebuilded .3ds / .cia corrupted.

So if you have any idea, workaround, or arguments I may have forgotten, please tell me !

**Comment by Asia81** [comment]
Maybe because the code.bin fail to decrypt
http://image.noelshack.com/fichiers/2017/36/3/1504670223-01.jpg

**Comment by dnasdw** [comment]
Add --exefs-top-auto-key option when extract exefs from cxi.
You can reference https://github.com/dnasdw/StellaGlowl10n project.
See this file: /CTR-P-BS3E/1_extract.bat.

PS:--exh-auto-key, --exefs-auto-key, --exefs-top-auto-key and --romfs-auto-key will remove after 3dstool v1.1.0.

**Comment by Asia81** [comment]
Thanks, after a lot of process I finally managed to have all working properly...
Thanks ;)

**Comment by Asia81** [comment]
When you say
PS:--exh-auto-key, --exefs-auto-key, --exefs-top-auto-key and --romfs-auto-key will remove after 3dstool v1.1.0.

Does it mean it will not be anymore to write that? Will be automatically used?

**Comment by dnasdw** [comment]
Yes.
